CREATE OR REPLACE DATABASE IOE_SCD2;
USE DATABASE IOE_SCD2;

CREATE OR REPLACE SCHEMA LANDING;
CREATE OR REPLACE SCHEMA STAGE;
CREATE OR REPLACE SCHEMA TEMP;
CREATE OR REPLACE SCHEMA TARGET;

CREATE OR REPLACE TABLE LANDING.SALES (
    Row_ID varchar,
    Order_ID varchar,
    Order_Date varchar,
    Ship_Date varchar,
    Ship_Mode varchar,
    Customer_ID varchar,
    Customer_Name varchar,
    Segment varchar,
    Country varchar,
    City varchar,
    State varchar,
    Postal_Code varchar,
    Region varchar,
    Product_ID varchar,
    Category varchar,
    Sub_Category varchar,
    Product_Name varchar,
    Sales varchar,
    Quantity varchar,
    Discount varchar,
    Profit varchar
);

CREATE STAGE IOE_SCD2.LANDING.CSV_FILE
  FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  );
LIST @LANDING.CSV_FILE;


SELECT COUNT(*) AS total_rows
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_CUSTOMER AS
SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(CUSTOMER_NAME) AS CUSTOMER_NAME,
    TRIM(SEGMENT) AS SEGMENT
FROM LANDING.SALES;
SELECT * FROM STAGE.STG_D_CUSTOMER LIMIT 10;

SELECT COUNT(*) AS total_customers FROM TEMP.TMP_D_CUSTOMER;
SELECT * FROM TEMP.TMP_D_CUSTOMER LIMIT 10;

CREATE OR REPLACE TABLE TARGET.TGT_D_CUSTOMER_SCD2 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR,
    START_DATE DATE,
    END_DATE DATE,
    CURRENT_FLAG BOOLEAN
);
SELECT COUNT(*) AS total_customers FROM TARGET.TGT_D_CUSTOMER_SCD2;
SELECT * 
FROM TARGET.TGT_D_CUSTOMER_SCD2 
LIMIT 10;

CREATE OR REPLACE VIEW STAGE.STG_D_PRODUCT AS
SELECT
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    TRIM(CATEGORY) AS CATEGORY,
    TRIM(SUB_CATEGORY) AS SUB_CATEGORY
FROM LANDING.SALES;


SELECT COUNT(*) FROM TEMP.TMP_D_PRODUCT; -- should match distinct products in CSV
SELECT * FROM TEMP.TMP_D_PRODUCT LIMIT 10;


CREATE OR REPLACE TABLE TARGET.TGT_D_PRODUCT_SCD2 (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    SUB_CATEGORY VARCHAR,
    START_DATE DATE,
    END_DATE DATE,
    CURRENT_FLAG BOOLEAN
);

SHOW TABLES IN SCHEMA TARGET;
DESCRIBE TABLE TARGET.TGT_D_PRODUCT_SCD2;
SELECT COUNT(*) FROM TARGET.TGT_D_PRODUCT_SCD2; -- should be 0

CREATE OR REPLACE VIEW STAGE.STG_D_LOCATION AS
SELECT
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(REGION) AS REGION,
    TRIM(STATE) AS STATE,
    TRIM(CITY) AS CITY,
    TRIM(POSTAL_CODE) AS POSTAL_CODE
FROM LANDING.SALES;



CREATE OR REPLACE TABLE TARGET.TGT_D_LOCATION (
    LOCATION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    COUNTRY VARCHAR,
    REGION VARCHAR,
    STATE VARCHAR,
    CITY VARCHAR,
    POSTAL_CODE VARCHAR
);

SELECT COUNT(*) FROM TARGET.TGT_D_LOCATION;

CREATE OR REPLACE VIEW STAGE.STG_D_SHIP_MODE AS
SELECT DISTINCT TRIM(SHIP_MODE) AS SHIP_MODE
FROM LANDING.SALES;

CREATE OR REPLACE TABLE TARGET.TGT_D_SHIP_MODE (
    SHIP_MODE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SHIP_MODE VARCHAR
);

SELECT * FROM TARGET.TGT_D_SHIP_MODE;


CREATE OR REPLACE VIEW STAGE.STG_F_SALES AS
SELECT
    TRIM(ORDER_ID) AS ORDER_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(REGION) AS REGION,
    TRIM(STATE) AS STATE,
    TRIM(CITY) AS CITY,
    TRIM(POSTAL_CODE) AS POSTAL_CODE,
    TO_DATE(ORDER_DATE, 'MM/DD/YYYY') AS ORDER_DATE,
    TO_DATE(SHIP_DATE, 'MM/DD/YYYY') AS SHIP_DATE,
    TRIM(SHIP_MODE) AS SHIP_MODE,
    CAST(QUANTITY AS FLOAT) AS QUANTITY,
    CAST(DISCOUNT AS FLOAT) AS DISCOUNT,
    CAST(SALES AS FLOAT) AS REVENUE,
    CAST(PROFIT AS FLOAT) AS PROFIT,
    CAST(SALES AS FLOAT) - CAST(PROFIT AS FLOAT) AS COST
FROM LANDING.SALES;

CREATE OR REPLACE TABLE TARGET.TGT_F_SALES (
    ORDER_ID VARCHAR PRIMARY KEY,
    CUSTOMER_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    LOCATION_KEY NUMBER,
    ORDER_DATE_KEY NUMBER,
    SHIP_DATE_KEY NUMBER,
    SHIP_MODE_KEY NUMBER,
    QUANTITY FLOAT,
    DISCOUNT FLOAT,
    REVENUE FLOAT,
    PROFIT FLOAT,
    COST FLOAT
);

SELECT f.CUSTOMER_ID, c.CUSTOMER_ID, c.CURRENT_FLAG
FROM STAGE.STG_F_SALES f
LEFT JOIN TARGET.TGT_D_CUSTOMER_SCD2 c
ON c.CUSTOMER_ID = f.CUSTOMER_ID AND c.CURRENT_FLAG = TRUE
LIMIT 10;
SELECT f.PRODUCT_ID, p.PRODUCT_ID, p.CURRENT_FLAG
FROM STAGE.STG_F_SALES f
LEFT JOIN TARGET.TGT_D_PRODUCT_SCD2 p
ON p.PRODUCT_ID = f.PRODUCT_ID AND p.CURRENT_FLAG = TRUE
LIMIT 10;
SELECT f.COUNTRY, f.STATE, l.COUNTRY, l.STATE
FROM STAGE.STG_F_SALES f
LEFT JOIN TARGET.TGT_D_LOCATION l
ON l.COUNTRY = f.COUNTRY AND l.STATE = f.STATE AND l.CITY = f.CITY
LIMIT 10;
SELECT f.ORDER_DATE, d.FULL_DATE
FROM STAGE.STG_F_SALES f
LEFT JOIN TARGET.TGT_D_DATE d
ON d.FULL_DATE = f.ORDER_DATE
LIMIT 10;


CREATE OR REPLACE VIEW STAGE.STG_D_DATE AS
SELECT
    TO_DATE(ORDER_DATE, 'MM/DD/YYYY') AS ORDER_DATE,
    TO_DATE(SHIP_DATE, 'MM/DD/YYYY') AS SHIP_DATE
FROM LANDING.SALES;


CREATE OR REPLACE TABLE TEMP.TMP_D_DATE (
    ORDER_DATE DATE,
    SHIP_DATE DATE
);

SELECT COUNT(*) AS total_rows FROM TEMP.TMP_D_DATE;
SELECT * FROM TEMP.TMP_D_DATE LIMIT 10;


CREATE OR REPLACE TABLE TARGET.TGT_D_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    FULL_DATE DATE,
    YEAR NUMBER,
    QUARTER NUMBER,
    MONTH NUMBER,
    MONTH_NAME VARCHAR,
    WEEK NUMBER,
    DAY NUMBER,
    DAY_OF_WEEK NUMBER,
    DAY_NAME VARCHAR,
    IS_WEEKEND BOOLEAN
);


SELECT COUNT(*) AS total_dates FROM TARGET.TGT_D_DATE;
SELECT * FROM TARGET.TGT_D_DATE LIMIT 10;

SHOW TABLES IN SCHEMA TEMP;
DESCRIBE TABLE TEMP.TMP_F_SALES;

SELECT COUNT(*) AS total_fact_rows FROM TEMP.TMP_F_SALES;
SELECT * FROM TEMP.TMP_F_SALES LIMIT 10;

SELECT COUNT(*) AS total_sales_rows FROM TARGET.TGT_F_SALES;
SELECT * FROM TARGET.TGT_F_SALES LIMIT 10;

CREATE OR REPLACE TABLE TARGET.TGT_D_CUSTOMER_SCD2 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR,
    START_DATE DATE DEFAULT CURRENT_DATE,
    END_DATE DATE DEFAULT DATE '9999-12-31',
    CURRENT_FLAG BOOLEAN DEFAULT TRUE
);
CREATE OR REPLACE TABLE TEMP.TMP_D_CUSTOMER AS
SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME, SEGMENT
FROM STAGE.STG_D_CUSTOMER;


-- Check total rows
SELECT COUNT(*) AS total_customers FROM TARGET.TGT_D_CUSTOMER_SCD2;

-- Check only current version of each customer
SELECT * 
FROM TARGET.TGT_D_CUSTOMER_SCD2 
WHERE CURRENT_FLAG = TRUE
LIMIT 10;

-- Check historical versions (if any updates were made)
SELECT * 
FROM TARGET.TGT_D_CUSTOMER_SCD2
ORDER BY CUSTOMER_ID, START_DATE;

CREATE OR REPLACE TABLE TARGET.TGT_D_PRODUCT_SCD2 (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    SUB_CATEGORY VARCHAR,
    START_DATE DATE DEFAULT CURRENT_DATE,
    END_DATE DATE DEFAULT DATE '9999-12-31',
    CURRENT_FLAG BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TEMP.TMP_D_PRODUCT AS
SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME, CATEGORY, SUB_CATEGORY
FROM STAGE.STG_D_PRODUCT;